### ISSUE TITLE
cctweets.php causing validation errors

### ISSUE THREAD

**Issue by philwareham** [MrQwest/CrCreatives#12]
It seems  cctweets.php file adds double instances of `a` link tags, which then causes validation errors. If you view source (or run the site through W3C validator) you will see the problem.

It's the `link_it` function (lines 19-27) causing the problem.

**Comment by MrQwest** [comment]
The `link_it` function is/was purely for parsing links into formed `<a>` link tags.  I wonder if somehow, it's already doing that and the `link_it` function is duplicating the code. Will look into this.

**Comment by MrQwest** [comment]
Fixed with latest commit.  For posterity, I removed the following line from the code: 

`$text= preg_replace("/@(\w+)/", '<a href="http://www.twitter.com/$1" rel="external">@$1</a>', $text);`
