### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by mikestreety** [MrQwest/CrCreatives#36]
Was looking at your date PHP and think it can be improved ( i _think_) - it depends on the criteria.
1. Is it always the last wednesday of the month? I know sometimes there are variations, but they are exceptions - correct?
2. Is it now always at Matthews Yard - the website mentions about alternating between two venues?
3. I've [asked @attending](https://twitter.com/mikestreety/status/525290378694782977) to see if we could automate setting up the attending page through an API, which would save you A LOT of time :smile:

**Comment by MrQwest** [comment]
Maaaate, an @attending API would be awesome (_cough cough_ @fulljames)

1) Yes, last wednesday of the month except generally Christmas as it's too congested.

2) Yes, always at Matthews Yard - should adjust that wording.

The site is due an overhaul now anyway so I was going to rewrite the copy when I rebuild the site.

**Comment by MrQwest** [comment]
But @mikestreety, please, if you can see improvements, improve!! I'm still learning and need to be shown errors / bad practices / ways to improve my code!

**Comment by mikestreety** [comment]
Will do when I get the time! :+1: 

Does @fulljames work on attending? 

If there in an api, we could set up a cron that triggers on the first of every month with predefined text which you can always tweak after.

**Comment by MrQwest** [comment]
You da' man!

He was working on Attending. Not sure if he's on another Makeshift project now (or something entirely different)... anything to automate the event setup would be spectacularly useful.... Next trick is to automate the monthly e-mails ;)

**Comment by mikestreety** [comment]
Ah didn't realise he worked for them.

Mailchimp has an API for that :wink:

**Comment by fulljames** [comment]
Its mostly Stef working on Attending at the moment but he's added a lot
recently. I think event series are on the way which should help with this.

I'm on leave next week or I'd come along to the meet up!

**Comment by MrQwest** [comment]
Cheers Steve, if he's in close vicinity, can you slip him a post-it note ;) Have a good holiday next week!

Mike, you have much experience with the mailchimp API?

**Comment by mikestreety** [comment]
Yes, a little - will have a look into it at some point and see if i can mock up a standalone example for you

**Comment by MrQwest** [comment]
You so smart! I'll take a look tonight too... Gives me something to do whilst the macbook is in the hospital!

**Comment by stefl** [comment]
Hey folks. I'm pretty keen on a simple API for Attending too. I have a simple JSON GET, but no create yet. I'm working on collections and series features too, as well as accepting payments. Maybe one of you would like to join the beta list and get access to some of that early?

**Comment by mikestreety** [comment]
Suggest we break this issue up into a few different ones addressing each one individually! :)

**Comment by MrQwest** [comment]
Agreed Mike, see #37 & #38 

@stefl that'd be pretty sweet to get a little beta action going on. Don't need payments or anything but series / create would be perfect :)

**Comment by mikestreety** [comment]
Hey @stefl, any movement on this? :smile:
