### ISSUE TITLE
Make a slack group

### ISSUE THREAD

**Issue by mikestreety** [MrQwest/CrCreatives#40]
You can make a slack team for Croydon creatives and accept any email address. Would mean people can sign up and chat generally or to specific people. Sort of like the CC directory :smile: 

Happy to set this up if you want?

**Comment by MrQwest** [comment]
@mikestreety nice idea!  I don't actually use Slack so haven't thought about this - but yes, if you've got the time, please do set one up :)

I'm also fleshing out the new CC design and will be pulling in your awesome code fixes sooon!

**Comment by mikestreety** [comment]
Yo, have created the group - unfortunately It's invite only (can;t sign up - we have to put the email addresses in). If you make a slack@croydoncreativ.es - people can email that and i'll invite them :smile: we can then make a form for the website

**Comment by MrQwest** [comment]
Yo @mikestreety, That email is all set up fella. What do you need from me?

**Comment by mikestreety** [comment]
Just logins for now (email me) and we'll think about how we get people to email! (Mention it in the next newsletter for now)

**Comment by MrQwest** [comment]
Wicked... Is that all up & running now? Can peeps start emailing slack@ and then they can get access (once you approve)?

**Comment by mikestreety** [comment]
Yup - email away!
